# Generated by Django 5.2 on 2025-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=20, unique=True, verbose_name='RA do Aluno')),
                ('registro_matricula', models.CharField(max_length=20, verbose_name='Registro de Matrícula')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10, verbose_name='Sexo')),
                ('nacionalidade', models.CharField(max_length=50, verbose_name='Nacionalidade')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('transferido', models.BooleanField(default=False, verbose_name='Transferido')),
                ('restricao_alimentar', models.TextField(blank=True, verbose_name='Restrição Alimentar')),
                ('uso_imagem', models.BooleanField(default=False, verbose_name='Autorização de Uso de Imagem')),
                ('saida_sem_acompanhante', models.BooleanField(default=False, verbose_name='Saída sem Acompanhante')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
        ),
    ]
