# Generated by Django 5.2 on 2025-04-10 18:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(max_length=100, verbose_name="Endereço"),
                ),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Complemento"
                    ),
                ),
                ("bairro", models.CharField(max_length=50, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=50, verbose_name="Cidade")),
            ],
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="bairro",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="complemento",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="registro_matricula",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="telefone",
        ),
        migrations.AddField(
            model_name="aluno",
            name="data_nascimento",
            field=models.DateField(
                default=datetime.date(2010, 1, 1), verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="nacionalidade",
            field=models.CharField(
                choices=[("BRASILEIRA", "BRASILEIRA"), ("ESTRANGEIRA", "ESTRANGEIRA")],
                max_length=20,
                verbose_name="Nacionalidade",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="restricao_alimentar",
            field=models.CharField(
                default="N/A", max_length=30, verbose_name="Restrição Alimentar"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="saida_sem_acompanhante",
            field=models.CharField(
                choices=[(True, "SIM"), (False, "NÃO")],
                max_length=3,
                verbose_name="Saída sem Acompanhante",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="serie",
            field=models.CharField(
                choices=[
                    ("1°A", "1°A"),
                    ("1°B", "1°B"),
                    ("1°C", "1°C"),
                    ("1°D", "1°D"),
                    ("2°A", "2°A"),
                    ("2°B", "2°B"),
                    ("2°C", "2°C"),
                    ("2°D", "2°D"),
                    ("3°A", "3°A"),
                    ("3°B", "3°B"),
                    ("3°C", "3°C"),
                    ("3°D", "3°D"),
                    ("4°A", "4°A"),
                    ("4°B", "4°B"),
                    ("4°C", "4°C"),
                    ("4°D", "4°D"),
                    ("5°A", "5°A"),
                    ("5°B", "5°B"),
                    ("5°C", "5°C"),
                    ("5°D", "5°D"),
                ],
                max_length=3,
                verbose_name="Série",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="sexo",
            field=models.CharField(
                choices=[
                    ("MASCULINO", "MASCULINO"),
                    ("FEMININO", "FEMININO"),
                    ("OUTRO", "OUTRO"),
                ],
                max_length=10,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="transferido",
            field=models.CharField(
                choices=[(True, "SIM"), (False, "NÃO")],
                max_length=3,
                verbose_name="Transferido",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="uso_imagem",
            field=models.CharField(
                choices=[(True, "SIM"), (False, "NÃO")],
                max_length=3,
                verbose_name="Autorização de Uso de Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="endereco",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="aluno.endereco"
            ),
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        primary_key=True,
                        serialize=False,
                        verbose_name="CPF do Responsável",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("rg", models.CharField(max_length=20, verbose_name="RG")),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("MASCULINO", "MASCULINO"),
                            ("FEMININO", "FEMININO"),
                            ("OUTRO", "OUTRO"),
                        ],
                        max_length=10,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        choices=[
                            ("BRASILEIRA", "BRASILEIRA"),
                            ("ESTRANGEIRA", "ESTRANGEIRA"),
                        ],
                        max_length=20,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("SOLTEIRO(A)", "SOLTEIRO(A)"),
                            ("CASADO(A)", "CASADO(A)"),
                            ("DIVORCIADO(A)", "DIVORCIADO(A)"),
                            ("VIÚVO(A)", "VIÚVO(A)"),
                        ],
                        max_length=20,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "tipo_responsavel",
                    models.CharField(
                        choices=[
                            ("PAI", "PAI"),
                            ("MÃE", "MÃE"),
                            ("TUTOR", "TUTOR"),
                            ("OUTRO", "OUTRO"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Responsável",
                    ),
                ),
                (
                    "tipo_responsavel_outro",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Se outro, especifique"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        default=datetime.date(2010, 1, 1),
                        verbose_name="Data de Nascimento",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("telefone", models.CharField(max_length=15, verbose_name="Telefone")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsaveis",
                        to="aluno.aluno",
                    ),
                ),
            ],
        ),
    ]
