# Generated by Django 5.2 on 2025-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0002_endereco_remove_aluno_bairro_remove_aluno_cep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="saida_sem_acompanhante",
            field=models.BooleanField(
                choices=[(True, "SIM"), (False, "NÃO")],
                verbose_name="Saída sem Acompanhante",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="transferido",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "SIM"), (False, "NÃO")],
                default=False,
                verbose_name="Transferido",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="uso_imagem",
            field=models.BooleanField(
                choices=[(True, "SIM"), (False, "NÃO")],
                verbose_name="Autorização de Uso de Imagem",
            ),
        ),
    ]
