# Generated by Django 5.2 on 2025-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0004_aluno_descricao_necessidade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aluno",
            old_name="transferido",
            new_name="ativo",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="descricao_necessidade",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="necessidades_especiais",
            field=models.CharField(
                default="N/A",
                max_length=30,
                verbose_name="Necessidades Especias (Nome e CID)",
            ),
        ),
    ]
