# Generated by Django 5.2 on 2025-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0005_rename_transferido_aluno_ativo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="ativo",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "SIM"), (False, "NÃO")],
                default=False,
                verbose_name="Ativo",
            ),
        ),
    ]
